In [1]:
# program 5-2. tensorflow and numpy
import tensorflow as tf
import numpy as np

t = tf.random.uniform([2,3],0,1)
n = np.random.uniform(0,1,[2,3])
print("tensorflow로 생성한 텐서 : \n", t, "\n")
print("numpy로 생성한 ndarray:\n",n, "\n")

# 텐서 t와 ndarray n의 덧셈
res = t + n
print("덧셈 결과: \n", res)

tensorflow로 생성한 텐서 : 
 tf.Tensor(
[[0.39681208 0.33872008 0.54051435]
 [0.04018259 0.62757576 0.8569298 ]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.42634961 0.11544006 0.86218165]
 [0.52833448 0.92341649 0.42129301]] 

덧셈 결과: 
 tf.Tensor(
[[0.8231617  0.45416015 1.402696  ]
 [0.5685171  1.5509923  1.2782228 ]], shape=(2, 3), dtype=float32)
