In [2]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

# read dataset and split into train and test
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(
    digit.data, digit.target, train_size=0.6
)

# train Perceptron using fit function
p = Perceptron(max_iter=1000, eta0=0.001, verbose=0)
p.fit(x_train, y_train) # train model

res = p.predict(x_test) # predict test data

# confusion matrix
conf = np.zeros((10, 10))
for i in range(len(res)):
    conf[res[i]][y_test[i]] += 1
print(conf)

# accuracy
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct / len(res)
print("테스트 집합에 대한 정확률은", accuracy*100, "%입니다.")

[[64.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 64.  1.  1.  3.  5.  1.  0.  4.  2.]
 [ 0.  0. 63.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0. 75.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. 68.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  0. 77.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0. 67.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  0. 72.  0.  0.]
 [ 0.  1.  2.  5.  4.  0.  0.  0. 68.  6.]
 [ 0.  0.  0.  1.  0.  2.  0.  1.  0. 53.]]
테스트 집합에 대한 정확률은 93.3240611961057 %입니다.
