In [1]:
# multi-layer perceptron recognizes MNIST datasets
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# read MNIST datasets and split into training set and test set

mnist = fetch_openml('mnist_784')
# [0,255] 범위의 ㄱ밧을 가진 mnist의 맵을 [0,1]로 정규화한다.
mnist.data = mnist.data/255.0
x_train = mnist.data[:60000]; x_test = mnist.data[60000:]
# label에 해당하는 mnist.target은 str형이므로 np.int16으로 16bit 정수형으로 변환
# int16으로 변환해야 confusion matrix를 그릴 때 index로 사용할 수 있다.
y_train = np.int16(mnist.target[:60000]); y_test = np.int16(mnist.target[60000:])

In [3]:
# create MLP classifier and train model

# 미니 배치의 크기를 큰 값인 512로 설정했다.
# 미니배치 크기를 크게 하면 오류 역전파 과정을 적게 수행해 학습 시간을 단축한다.
# MPLClassifier는 가중치를 초기화할 때와 학습 도중 미니배치 구성시 난수를 사용해서 실행마다 다른 결과를 얻게 된다.
mlp = MLPClassifier(hidden_layer_sizes=(100,100),
                    learning_rate_init=0.001,
                    batch_size=512, max_iter=300,
                    solver='adam', verbose=True)
mlp.fit(x_train, y_train)

Iteration 1, loss = 0.57602850
Iteration 2, loss = 0.21803623
Iteration 3, loss = 0.16310442
Iteration 4, loss = 0.13117015
Iteration 5, loss = 0.10864824
Iteration 6, loss = 0.09131156
Iteration 7, loss = 0.07979289
Iteration 8, loss = 0.06928326
Iteration 9, loss = 0.06136687
Iteration 10, loss = 0.05310815
Iteration 11, loss = 0.04714037
Iteration 12, loss = 0.04224384
Iteration 13, loss = 0.03777294
Iteration 14, loss = 0.03378822
Iteration 15, loss = 0.02996263
Iteration 16, loss = 0.02688236
Iteration 17, loss = 0.02324713
Iteration 18, loss = 0.02078110
Iteration 19, loss = 0.01831288
Iteration 20, loss = 0.01634801
Iteration 21, loss = 0.01441233
Iteration 22, loss = 0.01367649
Iteration 23, loss = 0.01156694
Iteration 24, loss = 0.01096885
Iteration 25, loss = 0.00938109
Iteration 26, loss = 0.00815161
Iteration 27, loss = 0.00780883
Iteration 28, loss = 0.00695054
Iteration 29, loss = 0.00479899
Iteration 30, loss = 0.00415812
Iteration 31, loss = 0.00352253
Iteration 32, los

MLPClassifier(batch_size=512, hidden_layer_sizes=(100, 100), max_iter=300,
              verbose=True)

In [4]:
# predict using test set
res = mlp.predict(x_test)

In [5]:
# confusion matrix
conf = np.zeros((10,10), dtype=np.int16)
for i in range(len(res)):
    conf[res[i]][y_test[i]] += 1
print(conf)

[[ 969    0    2    0    1    2    4    1    6    1]
 [   0 1127    1    0    0    0    2    4    0    3]
 [   1    2 1007    5    4    0    2    7    5    0]
 [   0    1    8  996    0   12    1    2    6    1]
 [   2    0    1    0  965    1    6    1    6    8]
 [   1    1    1    2    0  867    5    0    5    6]
 [   2    1    2    1    1    3  934    0    2    0]
 [   3    1    4    2    2    2    0 1003    3    3]
 [   1    2    6    2    1    4    4    2  937    2]
 [   1    0    0    2    8    1    0    8    4  985]]


In [6]:
# accuracy
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은", accuracy*100, "%입니다.")

테스트 집합에 대한 정확률은 97.89999999999999 %입니다.
